// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyChiTieu.Data;

#nullable disable

namespace QuanLyChiTieu.Migrations
{
    [DbContext(typeof(DataBase_DoAnContext))]
    [Migration("20250804120921_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyChiTieu.Models.ChiTieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TenChiTieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__ChiTieu__3214EC0748AA8F80");

                    b.HasIndex("DanhMucId");

                    b.HasIndex(new[] { "NgayChi" }, "IX_ChiTieu_NgayChi");

                    b.HasIndex(new[] { "NguoiDungId" }, "IX_ChiTieu_NguoiDungId");

                    b.ToTable("ChiTieu", null, t =>
                        {
                            t.HasTrigger("trg_CanhBaoVuotHanMuc");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MauSac")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("TuDongPhanLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id")
                        .HasName("PK__DanhMuc__3214EC07C2C35FB3");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.GioiHanChiTieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienToiDa")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__GioiHanC__3214EC078D4B0F17");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex(new[] { "Thang", "Nam" }, "IX_GioiHanChiTieu_Thang_Nam");

                    b.ToTable("GioiHanChiTieu");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.LichSuNhanNhac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LoaiNhanNhac")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id")
                        .HasName("PK__LichSuNh__3214EC07A3A7D1EB");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex(new[] { "NgayGui" }, "IX_LichSuNhanNhac_NgayGui");

                    b.ToTable("LichSuNhanNhac");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<TimeOnly?>("GioNhanNhac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time")
                        .HasDefaultValue(new TimeOnly(18, 0, 0));

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LoaiTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("NhanEmailNhacNho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("TanSuatNhanNhac")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("HangTuan");

                    b.HasKey("Id")
                        .HasName("PK__NguoiDun__3214EC07CF5C7E6E");

                    b.HasIndex(new[] { "Email" }, "UQ__NguoiDun__A9D10534A0F8E828")
                        .IsUnique();

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.Otp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaOtp")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaOTP");

                    b.Property<DateTime?>("ThoiGianTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id")
                        .HasName("PK__OTP__3214EC0766DF5851");

                    b.ToTable("OTP");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("DaDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__ThongBao__3214EC07F56E0324");

                    b.HasIndex(new[] { "NguoiDungId" }, "IX_ThongBao_NguoiDungId");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.TuKhoaDanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<string>("TuKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__TuKhoaDa__3214EC077923D733");

                    b.HasIndex("DanhMucId");

                    b.HasIndex(new[] { "TuKhoa" }, "IX_TuKhoaDanhMuc_TuKhoa");

                    b.ToTable("TuKhoaDanhMuc");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.VwThongKeChiTieu", b =>
                {
                    b.Property<int?>("Nam")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Thang")
                        .HasColumnType("int");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(38, 2)");

                    b.ToTable((string)null);

                    b.ToView("vw_ThongKeChiTieu", (string)null);
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.ChiTieu", b =>
                {
                    b.HasOne("QuanLyChiTieu.Models.DanhMuc", "DanhMuc")
                        .WithMany("ChiTieus")
                        .HasForeignKey("DanhMucId")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTieu__DanhMuc__440B1D61");

                    b.HasOne("QuanLyChiTieu.Models.NguoiDung", "NguoiDung")
                        .WithMany("ChiTieus")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTieu__NguoiDu__4316F928");

                    b.Navigation("DanhMuc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.GioiHanChiTieu", b =>
                {
                    b.HasOne("QuanLyChiTieu.Models.NguoiDung", "NguoiDung")
                        .WithMany("GioiHanChiTieus")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__GioiHanCh__Nguoi__46E78A0C");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.LichSuNhanNhac", b =>
                {
                    b.HasOne("QuanLyChiTieu.Models.NguoiDung", "NguoiDung")
                        .WithMany("LichSuNhanNhacs")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__LichSuNha__Nguoi__571DF1D5");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.ThongBao", b =>
                {
                    b.HasOne("QuanLyChiTieu.Models.NguoiDung", "NguoiDung")
                        .WithMany("ThongBaos")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ThongBao__NguoiD__4BAC3F29");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.TuKhoaDanhMuc", b =>
                {
                    b.HasOne("QuanLyChiTieu.Models.DanhMuc", "DanhMuc")
                        .WithMany("TuKhoaDanhMucs")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__TuKhoaDan__DanhM__52593CB8");

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.DanhMuc", b =>
                {
                    b.Navigation("ChiTieus");

                    b.Navigation("TuKhoaDanhMucs");
                });

            modelBuilder.Entity("QuanLyChiTieu.Models.NguoiDung", b =>
                {
                    b.Navigation("ChiTieus");

                    b.Navigation("GioiHanChiTieus");

                    b.Navigation("LichSuNhanNhacs");

                    b.Navigation("ThongBaos");
                });
#pragma warning restore 612, 618
        }
    }
}
